<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\VpnPlatform.Application\VpnPlatform.Application.csproj" />
    <ProjectReference Include="..\VpnPlatform.Domain\VpnPlatform.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.16">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.16" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.16" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageReference Include="QRCoder" Version="1.8.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.18.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.16" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.16" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.16" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="9.0.16" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.16" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.16" />
  </ItemGroup>
</Project>
