import { expect, test, type Page } from '@playwright/test'
import fs from 'node:fs'
import path from 'node:path'

type AdminSectionId = string

type AdminSmokeSection = {
  id: AdminSectionId
  route: string
}

const sectionLabels: Record<AdminSectionId, string> = {
  dashboard: 'Дашборд',
  users: 'Пользователи',
  payments: 'Оплаты',
  tariffs: 'Тарифы',
  referrals: 'Рефералы',
  subscriptions: 'Подписки',
  vpn: 'VPN-доступы',
  nodes: 'Серверы',
  panels: '3x-ui панели',
  support: 'Поддержка',
  audit: 'Аудит',
  bot: 'Telegram-бот',
  releases: 'Что нового',
  faq: 'FAQ',
  content: 'Контент сайта',
  scenarios: 'Сценарии',
  provisioning: 'Подготовка VPS'
}

function repoRoot() {
  return path.resolve(process.cwd(), '..')
}

function loadAdminSmokeSections() {
  const contractPath = path.join(repoRoot(), 'docs', 'admin-vps-smoke-sections.json')
  const contract = JSON.parse(fs.readFileSync(contractPath, 'utf8')) as { sections?: AdminSmokeSection[] }
  const loadedSections = contract.sections ?? []

  if (loadedSections.length === 0) {
    throw new Error('admin-vps-smoke-sections.json must list required admin sections.')
  }

  for (const section of loadedSections) {
    if (!sectionLabels[section.id]) {
      throw new Error(`Missing admin VPS smoke label for section ${section.id}.`)
    }
  }

  return loadedSections
}

const sections = loadAdminSmokeSections()

type SectionReport = {
  id: AdminSectionId
  route: string
  status: 'passed' | 'failed' | 'blocked' | 'skipped'
  httpStatus: number
  loaded: boolean
  evidence: string
}

type SmokeReport = {
  reportId: string
  environmentName: string
  apiBaseUrl: string
  adminWebUrl: string
  adminEmail: string
  smokeReportPath: string
  startedAt: string
  completedAt: string
  releaseId: string
  operator: string
  notes: string
  accountBootstrapChecked: boolean
  adminLoginPassed: boolean
  noJsErrors: boolean
  noUnauthorizedAfterLogin: boolean
  sections: SectionReport[]
}

function requireEnv(name: string) {
  const value = process.env[name]?.trim()
  if (!value) throw new Error(`${name} is required for admin VPS smoke.`)
  return value
}

function optionalEnv(name: string, fallback: string) {
  return process.env[name]?.trim() || fallback
}

function assertHttpUrl(value: string, name: string) {
  const url = new URL(value)
  if (url.protocol !== 'http:' && url.protocol !== 'https:') {
    throw new Error(`${name} must be an absolute http or https URL.`)
  }
}

function latestReleaseId() {
  const releasesPath = path.join(repoRoot(), 'backend', 'src', 'VpnPlatform.Api', 'AppReleases', 'releases.json')
  const releases = JSON.parse(fs.readFileSync(releasesPath, 'utf8')) as Array<{ releaseId?: string; releasedAt?: string; isActive?: boolean }>
  const latest = releases
    .filter((release) => release.isActive && release.releaseId)
    .sort((left, right) => Date.parse(right.releasedAt ?? '') - Date.parse(left.releasedAt ?? ''))[0]

  return latest?.releaseId ?? 'manual-admin-vps-browser-smoke'
}

function boolEnv(name: string) {
  return ['1', 'true', 'yes'].includes((process.env[name] ?? '').trim().toLowerCase())
}

function defaultReportPath() {
  return path.join(repoRoot(), 'tmp', 'admin-vps-smoke-report.json')
}

function sanitizeResponse(responseUrl: string, status: number) {
  const parsed = new URL(responseUrl)
  return `${status} ${parsed.pathname}`
}

function createReport(startedAt: Date, apiBaseUrl: string, adminWebUrl: string, adminEmail: string, smokeReportPath: string): SmokeReport {
  return {
    reportId: `admin-vps-smoke-${formatReportTimestamp(startedAt)}`,
    environmentName: optionalEnv('ADMIN_VPS_SMOKE_ENVIRONMENT', 'staging'),
    apiBaseUrl: apiBaseUrl.replace(/\/+$/, ''),
    adminWebUrl: adminWebUrl.replace(/\/+$/, ''),
    adminEmail,
    smokeReportPath,
    startedAt: startedAt.toISOString(),
    completedAt: startedAt.toISOString(),
    releaseId: optionalEnv('ADMIN_VPS_SMOKE_RELEASE_ID', latestReleaseId()),
    operator: optionalEnv('ADMIN_VPS_SMOKE_OPERATOR', process.env.USERNAME || 'manual-operator'),
    notes: 'Generated by live admin VPS browser smoke. No credentials, cookies, auth headers, tokens or screenshots are stored.',
    accountBootstrapChecked: boolEnv('ADMIN_VPS_SMOKE_ACCOUNT_BOOTSTRAP_CHECKED'),
    adminLoginPassed: false,
    noJsErrors: false,
    noUnauthorizedAfterLogin: false,
    sections: sections.map((section) => ({
      id: section.id,
      route: section.route,
      status: 'blocked',
      httpStatus: 0,
      loaded: false,
      evidence: `Not checked yet: ${section.id}.`
    }))
  }
}

function formatReportTimestamp(value: Date) {
  const pad = (part: number) => String(part).padStart(2, '0')
  return `${value.getUTCFullYear()}${pad(value.getUTCMonth() + 1)}${pad(value.getUTCDate())}-${pad(value.getUTCHours())}${pad(value.getUTCMinutes())}${pad(value.getUTCSeconds())}`
}

async function login(page: Page, adminWebUrl: string, email: string, password: string) {
  await page.goto(adminWebUrl, { waitUntil: 'domcontentloaded' })
  await expect(page.getByRole('heading', { name: 'Вход администратора' })).toBeVisible()
  await page.locator('.admin-login-form input[type="email"]').fill(email)
  await page.locator('.admin-login-form input[type="password"]').fill(password)
  await page.getByRole('button', { name: 'Войти в админку' }).click()
  await expect(page.getByRole('heading', { name: 'Дашборд' })).toBeVisible()
}

async function openSection(page: Page, label: string, id: AdminSectionId, route: string) {
  const tab = page.getByRole('tab', { name: label }).first()
  const sectionLink = page.getByRole('link', { name: label }).first()
  if (await tab.count() > 0) {
    await tab.click()
  } else if (await sectionLink.count() > 0) {
    await sectionLink.click()
  } else {
    const hash = new URL(route, 'http://admin-smoke.local').hash || `#${id}`
    await page.evaluate((value) => {
      window.location.hash = value
      window.dispatchEvent(new HashChangeEvent('hashchange'))
    }, hash)
  }

  await expect(page.locator(`#${id}`)).toBeVisible()
}

test('admin VPS smoke covers login and every admin section without storing secrets', async ({ page }) => {
  const apiBaseUrl = requireEnv('ADMIN_VPS_SMOKE_API_BASE_URL')
  const adminWebUrl = requireEnv('ADMIN_VPS_SMOKE_ADMIN_WEB_URL')
  const email = requireEnv('ADMIN_VPS_SMOKE_ADMIN_EMAIL')
  const password = requireEnv('ADMIN_VPS_SMOKE_ADMIN_PASSWORD')
  const outputPath = path.resolve(process.env.ADMIN_VPS_SMOKE_REPORT_PATH?.trim() || defaultReportPath())

  assertHttpUrl(apiBaseUrl, 'ADMIN_VPS_SMOKE_API_BASE_URL')
  assertHttpUrl(adminWebUrl, 'ADMIN_VPS_SMOKE_ADMIN_WEB_URL')

  const startedAt = new Date()
  const report = createReport(startedAt, apiBaseUrl, adminWebUrl, email, outputPath)
  const consoleErrors: string[] = []
  const failedResponses: string[] = []
  let collectFailedResponses = false
  let runError: string | null = null

  page.on('console', (message) => {
    if (message.type() === 'error') consoleErrors.push(message.text())
  })
  page.on('pageerror', (error) => consoleErrors.push(error.message))
  page.on('response', (response) => {
    if (collectFailedResponses && response.status() >= 400) {
      failedResponses.push(sanitizeResponse(response.url(), response.status()))
    }
  })

  try {
    await login(page, adminWebUrl, email, password)
    report.adminLoginPassed = true
    collectFailedResponses = true

    for (const sectionDefinition of sections) {
      const id = sectionDefinition.id
      const label = sectionLabels[id]
      const section = report.sections.find((item) => item.id === id)!
      const failedBefore = failedResponses.length

      try {
        await openSection(page, label, id, sectionDefinition.route)
        const sectionFailures = failedResponses.slice(failedBefore)
        section.httpStatus = sectionFailures.length === 0 ? 200 : Number(sectionFailures[0].split(' ', 1)[0])
        section.loaded = true
        section.status = sectionFailures.length === 0 ? 'passed' : 'failed'
        section.evidence = sectionFailures.length === 0
          ? `Section ${id} loaded on VPS admin; no failed API responses observed.`
          : `Section ${id} loaded, but failed responses were observed: ${sectionFailures.join('; ')}.`
      } catch (error) {
        section.httpStatus = 0
        section.loaded = false
        section.status = 'failed'
        section.evidence = `Section ${id} did not load: ${error instanceof Error ? error.message.split('\n')[0] : 'unknown error'}.`
      }
    }

    await page.getByRole('button', { name: 'Завершить сессию' }).click()
    await expect(page.getByRole('heading', { name: 'Вход администратора' })).toBeVisible()
  } catch (error) {
    runError = error instanceof Error ? error.message.split('\n')[0] : 'unknown admin VPS smoke error'
  } finally {
    report.completedAt = new Date().toISOString()
    report.noJsErrors = consoleErrors.length === 0
    report.noUnauthorizedAfterLogin = failedResponses.every((entry) => !entry.startsWith('401 ') && !entry.startsWith('403 '))

    fs.mkdirSync(path.dirname(outputPath), { recursive: true })
    fs.writeFileSync(outputPath, `${JSON.stringify(report, null, 2)}\n`, 'utf8')
  }

  expect(runError).toBeNull()
  expect(report.adminLoginPassed).toBe(true)
  expect(consoleErrors.length, 'console.error/pageerror count').toBe(0)
  expect(failedResponses.filter((entry) => entry.startsWith('401 ') || entry.startsWith('403 '))).toEqual([])
  expect(report.sections.filter((section) => section.status !== 'passed')).toEqual([])
})
